#file actions
file_show:
  url: /file/:id
  class: sfDoctrineRoute
  options: { model: ManagedFile, type: object }
  param: { module: file, action: show }
  requirements:
    id: \d+

file_upload:
  url: /file/create/directory/:id
  class: sfDoctrineRoute
  options: { model: FileDirectory, type: object }
  param: { module: file, action: create }
  requirements:
    id: \d+
    sf_method: [post]

file_download:
  url: /file/:id/download
  class: sfDoctrineRoute
  options: { model: ManagedFile, type: object }
  param: { module: file, action: download }
  requirements:
    id: \d+

file_edit:
  url: /file/:id/edit
  class: sfDoctrineRoute
  options: { model: ManagedFile, type: object }
  param: { module: file, action: edit }
  requirements:
    id: \d+

file_update:
  url: /file/:id/update
  class: sfDoctrineRoute
  options: { model: ManagedFile, type: object }
  param: { module: file, action: update }
  requirements:
    sf_method: [post]
    id: \d+

file_nodefaults:
  url: /file/*
  options: { module: default, action: error }

#directory actions
directory_show:
  url: /directory/:id
  class: sfDoctrineRoute
  options: { model: FileDirectory, type: object }
  param: { module: directory, action: show }
  requirements:
    id: \d+

directory_create:
  url: /directory/create
  param: { module: directory, action: create }
  requirements:
    sf_method: [post]

directory_list:
  url: /directory/list
  param: { module: directory, action: list }

directory_list_member:
  url: /directory/list/:id
  param: { module: directory, action: list }
  requirements:
    id: \d+

directory_edit_name:
  url: /directory/:id/edit
  class: sfDoctrineRoute
  options: { model: FileDirectory, type: object }
  param: { module: directory, action: edit }
  requirements:
    id: \d+
    sf_method: [put]

directory_publish:
  url: /directory/:id/publish
  class: sfDoctrineRoute
  options: { model: FileDirectory, type: object }
  param: { module: directory, action: publish }
  requirements:
    id: \d+
    sf_method: [put]

directory_delete:
  url: /directory/:id/delete
  class: sfDoctrineRoute
  options: { model: FileDirectory, type: object }
  param: { module: directory, action: delete }
  requirements:
    id: \d+
    sf_method: [delete]

directory_nodefaults:
  url: /directory/*
  options: { module: default, action: error }
