#file actions
file_show:
  url: /file/:id
  class: opDynamicAclRoute
  options: { model: ManagedFile, type: object, privilege: view }
  param: { module: file, action: show }
  requirements:
    id: \d+

file_upload:
  url: /file/create/directory/:id
  class: opDynamicAclRoute
  options: { model: FileDirectory, type: object, privilege: upload }
  param: { module: file, action: create }
  requirements:
    id: \d+
    sf_method: [post]

file_upload_community:
  url: /file/create/community/:id
  class: sfDoctrineRoute
  options: { model: Community, type: object }
  param: { module: file, action: createFileCommunity }
  requirements:
    id: \d+
    sf_method: [post]

file_upload_member:
  url: /file/create/member/:id
  class: sfDoctrineRoute
  options: { model: Member, type: object }
  param: { module: file, action: createFileMember }
  requirements:
    id: \d+
    sf_method: [post]

file_download:
  url: /file/:id/download
  class: opDynamicAclRoute
  options: { model: ManagedFile, type: object, privilege: view }
  param: { module: file, action: download }
  requirements:
    id: \d+

file_edit_name:
  url: /file/:id/edit
  class: opDynamicAclRoute
  options: { model: ManagedFile, type: object, privilege: edit }
  param: { module: file, action: edit }
  requirements:
    id: \d+
    sf_method: [put]

file_delete:
  url: /file/:id/delete
  class: opDynamicAclRoute
  options: { model: ManagedFile, type: object, privilege: delete }
  param: { module: file, action: delete }
  requirements:
    sf_method: [delete]
    id: \d+

file_list_member:
  url: /file/listMember/:id
  class: sfDoctrineRoute
  options: { model: Member, type: object }
  param: { module: file, action: listMember }
  requirements:
    id: \d+

file_list_community:
  url: /file/listCommunity/:id
  class: sfDoctrineRoute
  options: { model: Community, type: object }
  param: { module: file, action: listCommunity }
  requirements:
    id: \d+

file_nodefaults:
  url: /file/*
  options: { module: default, action: error }

#directory actions
directory_show:
  url: /directory/:id
  class: opDynamicAclRoute
  options: { model: FileDirectory, type: object, privilege: view }
  param: { module: directory, action: show }
  requirements:
    id: \d+

directory_create:
  url: /directory/create
  param: { module: directory, action: create }
  requirements:
    sf_method: [post]

directory_list:
  url: /directory/list
  param: { module: directory, action: list }

directory_list_member:
  url: /directory/list/:id
  class: sfDoctrineRoute
  options: { model: Member, type: object }
  param: { module: directory, action: list }
  requirements:
    id: \d+

directory_list_community:
  url: /directory/listCommunity/:id
  class: sfDoctrineRoute
  options: { model: community, type: object }
  param: { module: directory, action: listCommunity }
  requirements:
    id: \d+

directory_edit_name:
  url: /directory/:id/edit
  class: opDynamicAclRoute
  options: { model: FileDirectory, type: object, privilege: edit }
  param: { module: directory, action: edit }
  requirements:
    id: \d+
    sf_method: [put]

directory_publish:
  url: /directory/:id/publish
  class: opDynamicAclRoute
  options: { model: FileDirectory, type: object, privilege: edit }
  param: { module: directory, action: publish }
  requirements:
    id: \d+
    sf_method: [put]

directory_delete:
  url: /directory/:id/delete
  class: opDynamicAclRoute
  options: { model: FileDirectory, type: object, privilege: edit }
  param: { module: directory, action: delete }
  requirements:
    id: \d+
    sf_method: [delete]

directory_nodefaults:
  url: /directory/*
  options: { module: default, action: error }
