<?php

/**
 * PluginDirectoryConfigTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginDirectoryConfigTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginDirectoryConfigTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginDirectoryConfig');
    }
}