<?php

/**
 * PluginDirectoryConfigTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    opFileManagedPlugin
 * @author     Seiji Amashige <amashige@tejimaya.com>
 */
class PluginDirectoryConfigTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object PluginDirectoryConfigTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('PluginDirectoryConfig');
  }

  public function getCommunityConfigByDirectoryId($directoryId)
  {
    return $this->getDirectoryConfigQuery($directoryId)
      ->andWhere('community_id <> ""')
      ->fetchOne();
  }

  public function getDirectoryConfigQuery($directoryId)
  {
    return $this->createQuery()
      ->where('directory_id = ?', $directoryId);
  }

  public function getDirectoryIdsByCommunityId($communityId)
  {
    $results = $this->createQuery()
      ->where('community_id = ?', $communityId)
      ->select('directory_id')
      ->execute(array(), Doctrine::HYDRATE_NONE);
    $max = count($results);
    $ids = array();
    for ($i = 0; $i < $max; $i++)
    {
      $ids[] = $results[$i][0];
    }

    return $ids;
  }
}
