<?php

/**
 * PluginManagedFileTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginManagedFileTable extends opAccessControlDoctrineTable
{
  /**
   * Returns an instance of this class.
   *
   * @return object PluginManagedFileTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('PluginManagedFile');
  }

  public function getDirectoryFileList($directoryId)
  {
    return ManagedFileQuery::getFileListQueryByDirectoryId($directoryId);
  }

  public function getMemberFileList($memberId)
  {
    return ManagedFileQuery::getMemberFileListQuery($memberId);
  }

  public function getCommunityFileList($communityId)
  {
    return ManagedFileQuery::getCommunityFileListQuery($communityId);
  }

  public function getPublicFileList($searchParameter = null)
  {
    return ManagedFileQuery::getPublicFileListQuery($searchParameter);
  }

  public function appendRoles(Zend_Acl $acl)
  {
    return $acl
      ->addRole(new Zend_Acl_Role('reject'))
      ->addRole(new Zend_Acl_Role('everyone'))
      ->addRole(new Zend_Acl_Role('member'), 'everyone')
      ->addRole(new Zend_Acl_Role('author'), 'member')
      ->addRole(new Zend_Acl_Role('admin'), 'author');
  }

  public function appendRules(Zend_Acl $acl, $resource = null)
  {
    $directory = $resource ? $resource->FileDirectory : null;
    if (!$directory)
    {
      throw new LogicException('ManagedFileTable::appendRules resource is null.');
    }

    # all community member can view file
    $acl->allow('member', $resource, 'view');
    $acl->allow('author', $resource, 'edit');
    $acl->allow('author', $resource, 'delete');

    if ('public' === $directory->type)
    {
      $acl->allow('everyone', $resource, 'view');
    }
    elseif ('community' === $directory->type)
    {
      if ('public' === $directory->getConfig()->getCommunityConfig('file_public_flag'))
      {
        $acl->allow('everyone', $resource, 'view');
      }
    }

    return $acl;
  }
}
