<?php

/**
 * PluginDirectoryConfig
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    opFileManagedPlugin
 * @author     Seiji Amashige <amashige@tejimaya.com>
 */
abstract class PluginDirectoryConfig extends BaseDirectoryConfig
{
  public function create($directoryId, $communityId = null)
  {
    $this->setDirectoryId($directoryId);
    $this->setCommunityId($communityId);

    return $this->save();
  }

  public function updateCommunityId($communityId)
  {
    $this->setCommunityId($communityId);

    return $this->save();
  }
}
