<?php

/**
 * PluginFileDirectoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginFileDirectoryTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object PluginFileDirectoryTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('PluginFileDirectory');
  }

  public function getDirectoryListByMemberId($memberId, $isOpenOnly = false)
  {
    $q = $this->createQuery()
      ->where('member_id = ?', $memberId);

    if ($isOpenOnly)
    {
      $q->andWhere('is_open = ?', true);
    }

    return $q->execute();
  }
}
