<?php

/**
 * PluginDirectoryConfig
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    opFileManagedPlugin
 * @author     Seiji Amashige <amashige@tejimaya.com>
 */
abstract class PluginDirectoryConfig extends BaseDirectoryConfig
{
}
