<?php

/**
 * PluginFileDirectoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginFileDirectoryTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object PluginFileDirectoryTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('PluginFileDirectory');
  }

  public function getDirectoryListByMemberId($memberId)
  {
    return $this->createQuery()
      ->where('member_id = ?', $memberId)
      ->execute();
  }
}
