<?php

/**
 * PluginManagedFileTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginManagedFileTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object PluginManagedFileTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('PluginManagedFile');
  }

  public function getDirectoryFileListPager($directoryId, $page = null)
  {
    $q = ManagedFileQuery::getFileListQueryByDirectoryId($directoryId);

    $size = sfConfig::get('app_file_list_max_size', 10);

    return $this->getPager($q, $size, $page);
  }

  public function getCommunityFileListPager($communityId, $page = null)
  {
    $q = ManagedFileQuery::getCommunityFileListQuery($communityId);

    $size = sfConfig::get('app_file_list_max_size', 10);

    return $this->getPager($q, $size, $page);
  }

  private function getPager(Doctrine_Query $q, $size, $page = 1)
  {
    $pager = new sfDoctrinePager('ManagedFile', $size);
    $pager->setQuery($q);
    $pager->setPage($page);

    return $pager;
  }
}
