all:
  .array:
    opFileManagePluginWidgets:
      use_private_directory:
        widget: sfWidgetFormSelectRadio
        validator: sfValidatorChoice
        widgetOptions:
          choices: { 1: Use, 0: Not use }
        validatorOptions:
          choices: [ 1, 0 ]
        default: 0
      use_community_directory:
        widget: sfWidgetFormSelectRadio
        validator: sfValidatorChoice
        widgetOptions:
          choices: { 1: Use, 0: Not use }
        validatorOptions:
          choices: [ 1, 0 ]
        default: 0
